(function () {
  window.GUIA2_QUIZ_VARIANTS = {
    A: [
      {
        id: "q1",
        topic: "Extensiones de archivo",
        prompt: "Un comerciante de Puerto Boyaca recibe por correo un archivo llamado 'factura.exe' supuestamente de un proveedor. Como tecnico, que extension representa el mayor riesgo de seguridad y debe alertarte?",
        options: [
          ".pdf, porque solo Acrobat lo puede abrir.",
          ".exe, porque es un ejecutable que puede contener codigo malicioso.",
          ".docx, porque ocupa mucho espacio.",
          ".jpg, porque comprime imagenes.",
        ],
        correctIndex: 1,
      },
      {
        id: "q2",
        topic: "Suite ofimatica",
        prompt: "Para construir el archivo 'Control_Ventas_[Negocio].xlsx' con formulas como =SUMA() y =PROMEDIO() para el actor productivo, que aplicacion ofimatica corresponde?",
        options: [
          "Microsoft Word o LibreOffice Writer",
          "Microsoft Excel o LibreOffice Calc",
          "Microsoft PowerPoint o LibreOffice Impress",
          "Bloc de notas",
        ],
        correctIndex: 1,
      },
      {
        id: "q3",
        topic: "Sistemas operativos",
        prompt: "Un tendero del Magdalena Medio tiene un computador de baja gama con 1 GB de RAM y 100 GB de disco. Cual de estos sistemas operativos es el mas adecuado?",
        options: [
          "Windows 11, porque es el mas reciente.",
          "macOS, porque es el mas seguro.",
          "Linux Lite, porque opera con requerimientos minimos bajos.",
          "Windows Server, porque maneja varios usuarios.",
        ],
        correctIndex: 2,
      },
      {
        id: "q4",
        topic: "Ciberseguridad",
        prompt: "El actor productivo recibe un correo de su banco que pide sus credenciales con un enlace a una pagina que parece oficial. Como se llama esta amenaza y que deberias indicarle?",
        options: [
          "Spam, ignorar el mensaje sin mas.",
          "Phishing, no hacer clic ni entregar credenciales y reportar a su banco.",
          "Spyware, comprar un antivirus de paga inmediatamente.",
          "Adware, cambiar el navegador.",
        ],
        correctIndex: 1,
      },
      {
        id: "q5",
        topic: "Herramientas colaborativas",
        prompt: "Un equipo necesita compartir documentos y editarlos al mismo tiempo desde distintos computadores. Que herramienta en la nube es la mas adecuada?",
        options: [
          "WhatsApp Desktop",
          "Google Drive / Google Docs o Microsoft 365",
          "VLC Media Player",
          "Bloc de notas",
        ],
        correctIndex: 1,
      },
      {
        id: "q6",
        topic: "Ciberseguridad",
        prompt: "Cual de las siguientes es una contrasena fuerte recomendable para el correo del actor productivo?",
        options: [
          "123456",
          "elnombredelnegocio",
          "T3ndero#2026!Verde",
          "password",
        ],
        correctIndex: 2,
      },
      {
        id: "q7",
        topic: "Suite ofimatica",
        prompt: "El actor productivo necesita un documento de texto con encabezado, tabla comparativa y conclusion. Que aplicacion es la indicada y en que formato nativo lo guarda LibreOffice Writer?",
        options: [
          "LibreOffice Calc en formato .ods",
          "LibreOffice Writer en formato .odt",
          "LibreOffice Impress en formato .odp",
          "LibreOffice Draw en formato .odg",
        ],
        correctIndex: 1,
      },
      {
        id: "q8",
        topic: "Herramientas colaborativas",
        prompt: "El gerente del negocio pide una reunion virtual con su sucursal en otra ciudad y compartir pantalla mostrando una hoja de calculo. Cual de estas opciones es adecuada?",
        options: [
          "Microsoft Excel sin conexion.",
          "Google Meet, Microsoft Teams o Zoom con la funcion de compartir pantalla.",
          "Un USB con los archivos.",
          "El Bloc de notas en modo presentacion.",
        ],
        correctIndex: 1,
      },
      {
        id: "q9",
        topic: "Solucion digital",
        prompt: "Al disenar la 'Guia de uso rapido' para un tendero de 50 anos que nunca uso Excel, cual es el criterio mas importante?",
        options: [
          "Usar muchos tecnicismos para que se vea profesional.",
          "Lenguaje sencillo, instrucciones paso a paso y capturas de pantalla.",
          "Escribirla en ingles para que se vea moderna.",
          "Hacerla en formato de video unicamente.",
        ],
        correctIndex: 1,
      },
      {
        id: "q10",
        topic: "Buenas practicas",
        prompt: "Despues de construir la herramienta digital y entregarla al actor productivo, donde debes guardar la version final con la estructura 01_Perfil_Digital, 02_Herramienta, 03_Guia_Uso_Rapido, 04_Presentacion?",
        options: [
          "Solo en el escritorio del equipo del aprendiz.",
          "En una carpeta compartida de Google Drive, organizada y compartida con el instructor.",
          "Imprimirlo en papel y entregarlo fisicamente.",
          "En el correo personal del aprendiz.",
        ],
        correctIndex: 1,
      },
    ],
    B: [
      {
        id: "q1",
        topic: "Extensiones de archivo",
        prompt: "Tu actor productivo tiene un archivo de Microsoft Word de 2007 o superior. Cual de estas extensiones le corresponde?",
        options: [
          ".doc",
          ".docx",
          ".xlsx",
          ".pptx",
        ],
        correctIndex: 1,
      },
      {
        id: "q2",
        topic: "Suite ofimatica",
        prompt: "El comerciante quiere mostrar a sus clientes una presentacion de 5 diapositivas con su producto. Que aplicacion debe usar?",
        options: [
          "LibreOffice Calc o Microsoft Excel",
          "LibreOffice Writer o Microsoft Word",
          "LibreOffice Impress o Microsoft PowerPoint",
          "WinRAR",
        ],
        correctIndex: 2,
      },
      {
        id: "q3",
        topic: "Sistemas operativos",
        prompt: "Windows 11 exige minimo procesador de 64 bits con 2 nucleos a 1 GHz, 4 GB de RAM y 64 GB de almacenamiento. Si el equipo del actor productivo solo tiene 2 GB de RAM, que es lo mas correcto recomendar?",
        options: [
          "Instalar Windows 11 igual, el sistema se ajustara.",
          "Buscar un sistema operativo con menos requerimientos como Linux Lite o un Windows mas antiguo.",
          "Cambiar el procesador inmediatamente.",
          "Vender el equipo y dejarlo sin computador.",
        ],
        correctIndex: 1,
      },
      {
        id: "q4",
        topic: "Ciberseguridad",
        prompt: "Un malware que cifra los archivos del usuario y exige un pago para devolverlos se llama:",
        options: [
          "Spyware",
          "Ransomware",
          "Adware",
          "Cookie",
        ],
        correctIndex: 1,
      },
      {
        id: "q5",
        topic: "Herramientas colaborativas",
        prompt: "Necesitas enviar al instructor un archivo de mas de 5 MB. Cual herramienta es la mas adecuada para ese envio?",
        options: [
          "Adjuntarlo en un mensaje de SMS.",
          "WeTransfer u otra plataforma de envio de archivos grandes.",
          "Imprimirlo en hojas.",
          "Copiarlo en un CD y enviarlo por correo postal.",
        ],
        correctIndex: 1,
      },
      {
        id: "q6",
        topic: "Ciberseguridad",
        prompt: "El actor productivo no tiene copia de seguridad de su archivo de ventas. Cual recomendacion le das primero?",
        options: [
          "No hacer nada, los datos casi nunca se pierden.",
          "Configurar respaldo automatico en la nube (Google Drive u OneDrive) ademas de una copia local en USB.",
          "Imprimir todos los archivos cada dia.",
          "Borrar los archivos antiguos para que no estorben.",
        ],
        correctIndex: 1,
      },
      {
        id: "q7",
        topic: "Suite ofimatica",
        prompt: "En Excel, la formula =C2*D2 sirve para:",
        options: [
          "Sumar dos celdas",
          "Multiplicar el valor de la celda C2 por el valor de la celda D2",
          "Concatenar texto",
          "Convertir a PDF",
        ],
        correctIndex: 1,
      },
      {
        id: "q8",
        topic: "Herramientas colaborativas",
        prompt: "Para crear el logo y la pieza visual del negocio (afiches, redes sociales) con plantillas faciles de editar, cual es la herramienta mas adecuada?",
        options: [
          "CrystalDiskInfo",
          "Canva",
          "VLC Media Player",
          "Bloc de notas",
        ],
        correctIndex: 1,
      },
      {
        id: "q9",
        topic: "Solucion digital",
        prompt: "Al definir el problema digital del actor productivo, cual es la mejor practica?",
        options: [
          "Escribir tantas paginas como sea posible.",
          "Resumir en maximo tres oraciones cual es el principal obstaculo digital y que consecuencia tiene.",
          "Copiar el problema de otra empresa.",
          "Saltarse este paso e ir directo a la herramienta.",
        ],
        correctIndex: 1,
      },
      {
        id: "q10",
        topic: "Buenas practicas",
        prompt: "Antes de instalar cualquier programa en el equipo del actor productivo, cual es la practica MAS segura?",
        options: [
          "Descargarlo del primer resultado de Google.",
          "Copiarlo de un USB de un companero.",
          "Descargarlo directamente del sitio oficial del fabricante.",
          "Instalarlo sin revisar nada.",
        ],
        correctIndex: 2,
      },
    ],
    C: [
      {
        id: "q1",
        topic: "Extensiones de archivo",
        prompt: "Un archivo comprimido enviado por el proveedor puede tener cual de estas extensiones?",
        options: [
          ".rar o .zip",
          ".docx",
          ".jpg",
          ".mp3",
        ],
        correctIndex: 0,
      },
      {
        id: "q2",
        topic: "Suite ofimatica",
        prompt: "El actor productivo necesita una tabla con formulas para calcular su inventario. Que tres programas de la suite ofimatica abarcan texto, calculos y presentaciones respectivamente?",
        options: [
          "Word, Excel y PowerPoint (Microsoft) o Writer, Calc e Impress (LibreOffice)",
          "Outlook, Skype y Teams",
          "Photoshop, Illustrator y Premiere",
          "VLC, WinRAR y Bloc de notas",
        ],
        correctIndex: 0,
      },
      {
        id: "q3",
        topic: "Sistemas operativos",
        prompt: "Al recomendar un sistema operativo a un actor productivo, sobre que debes basar tu decision como tecnico?",
        options: [
          "La opinion personal del vendedor de la tienda.",
          "Los requerimientos minimos oficiales (CPU, RAM, disco) y el presupuesto del usuario.",
          "Lo que diga el primer video de YouTube que aparezca.",
          "Solo el sistema mas reciente, sin importar el equipo.",
        ],
        correctIndex: 1,
      },
      {
        id: "q4",
        topic: "Ciberseguridad",
        prompt: "Cual de estas redes representa un riesgo mayor para los datos del actor productivo si se conecta sin proteccion?",
        options: [
          "La red Wi-Fi privada del negocio con contrasena fuerte.",
          "Una red Wi-Fi publica gratuita en un parque o cafeteria sin VPN.",
          "Conexion por cable ethernet del local.",
          "Datos moviles 4G del telefono personal.",
        ],
        correctIndex: 1,
      },
      {
        id: "q5",
        topic: "Herramientas colaborativas",
        prompt: "El gerente quiere que su equipo edite un mismo documento simultaneamente desde distintos dispositivos. Que opcion lo permite directamente?",
        options: [
          "Microsoft Word instalado solo en un computador.",
          "Un Google Doc o Word Online compartido con permisos de edicion.",
          "Imprimir el documento y pasarlo de mano en mano.",
          "Guardarlo en un USB y prestarlo.",
        ],
        correctIndex: 1,
      },
      {
        id: "q6",
        topic: "Ciberseguridad",
        prompt: "Al detectar un correo de phishing dirigido al actor productivo, cual debe ser la accion correcta?",
        options: [
          "Hacer clic en el enlace para ver que pasa.",
          "Responder al remitente con sus datos para verificar.",
          "No hacer clic en enlaces, no entregar credenciales y reportar el correo como phishing.",
          "Reenviarlo a todos sus contactos para advertir.",
        ],
        correctIndex: 2,
      },
      {
        id: "q7",
        topic: "Suite ofimatica",
        prompt: "Una funcion clave de Excel/Calc para resumir datos de ventas es:",
        options: [
          "Funciones como SUMA(), PROMEDIO() y MAX() y graficos.",
          "Cambiar el color del fondo.",
          "Imprimir el documento en blanco y negro.",
          "Eliminar todas las hojas de calculo.",
        ],
        correctIndex: 0,
      },
      {
        id: "q8",
        topic: "Comunicacion digital",
        prompt: "Al redactar un correo de entrega al instructor, que debe incluir un correo profesional?",
        options: [
          "Solo el archivo adjunto sin texto.",
          "Asunto claro, saludo formal, descripcion del adjunto y despedida profesional.",
          "Emojis y mensajes informales.",
          "Solo el numero de telefono del aprendiz.",
        ],
        correctIndex: 1,
      },
      {
        id: "q9",
        topic: "Solucion digital",
        prompt: "Al disenar una herramienta digital personalizada para el actor productivo (plantilla de Excel, modelo de carta, presentacion), que principio debe respetarse?",
        options: [
          "Usar siempre la herramienta mas avanzada del mercado.",
          "Adaptar la herramienta al contexto del usuario para que pueda operarla de forma autonoma.",
          "Disenarla sin probarla con el usuario.",
          "Hacerla compleja para impresionar al instructor.",
        ],
        correctIndex: 1,
      },
      {
        id: "q10",
        topic: "Buenas practicas",
        prompt: "Despues de presentar la solucion al grupo y recibir retroalimentacion con la rubrica de evaluacion, que sigue?",
        options: [
          "Ignorar las observaciones porque la solucion ya esta entregada.",
          "Realizar los ajustes senalados y guardar la version final en la carpeta de Drive con la estructura indicada.",
          "Borrar todos los archivos y empezar de cero.",
          "Enviar todo solo por WhatsApp.",
        ],
        correctIndex: 1,
      },
    ],
  };
})();
