(function () {
  window.GUIA6_QUIZ_VARIANTS = {
    A: [
      {
        id: "q1",
        topic: "Ofimatica",
        prompt: "Un tecnico debe dejar listos los equipos de una empresa para trabajo de oficina. Que suite ofimatica de codigo abierto puede instalar sin costo de licencia?",
        options: [
          "Microsoft Office 365",
          "LibreOffice",
          "Adobe Acrobat Pro",
          "AutoCAD",
        ],
        correctIndex: 1,
      },
      {
        id: "q2",
        topic: "Ofimatica",
        prompt: "El gerente de TechBoyCa pide que los empleados puedan escribir informes, hacer calculos en tablas y crear presentaciones. Que tres programas de LibreOffice cubren esas tres tareas?",
        options: [
          "Writer, Calc e Impress",
          "Draw, Base y Math",
          "Writer, Draw y Calc",
          "Impress, Math y Base",
        ],
        correctIndex: 0,
      },
      {
        id: "q3",
        topic: "Antivirus",
        prompt: "Al revisar los equipos nuevos de TechBoyCa, el tecnico encuentra que el antivirus esta desactualizado. Cual es el principal riesgo de esa situacion?",
        options: [
          "El equipo consume mas energia electrica.",
          "No detecta amenazas recientes porque desconoce sus firmas.",
          "El procesador trabaja mas lento permanentemente.",
          "Se pierden los archivos de Office.",
        ],
        correctIndex: 1,
      },
      {
        id: "q4",
        topic: "Seguridad",
        prompt: "Un usuario recibe un correo que parece de su banco, pide sus credenciales y tiene un enlace a una pagina falsa. Como se llama esta amenaza?",
        options: [
          "Troyano",
          "Ransomware",
          "Phishing",
          "Rootkit",
        ],
        correctIndex: 2,
      },
      {
        id: "q5",
        topic: "Diagnostico",
        prompt: "El tecnico quiere ver en tiempo real cuanta CPU y RAM consume cada proceso en Windows. Que herramienta usa?",
        options: [
          "Bloc de notas",
          "Administrador de tareas",
          "Panel de control de red",
          "Desfragmentador de disco",
        ],
        correctIndex: 1,
      },
      {
        id: "q6",
        topic: "Instalacion",
        prompt: "Antes de instalar cualquier programa en los equipos de la empresa, cual es la practica mas segura?",
        options: [
          "Descargarlo desde el primer resultado de busqueda en Google.",
          "Copiarlo de un USB que trajo un companero.",
          "Descargarlo directamente del sitio oficial del fabricante.",
          "Instalarlo sin revisar el instalador.",
        ],
        correctIndex: 2,
      },
      {
        id: "q7",
        topic: "Navegadores",
        prompt: "El tecnico instala un navegador web en los equipos. Que funcion cumple principalmente el navegador en el trabajo diario de una oficina?",
        options: [
          "Administrar la red local del edificio.",
          "Acceder a sitios web, plataformas en linea y servicios de correo.",
          "Formatear discos duros.",
          "Instalar controladores de impresora.",
        ],
        correctIndex: 1,
      },
      {
        id: "q8",
        topic: "Colaboracion",
        prompt: "La empresa quiere que sus empleados compartan documentos y los editen al mismo tiempo desde diferentes computadores. Que herramienta en la nube es mas adecuada?",
        options: [
          "WhatsApp Desktop",
          "Google Drive o Microsoft OneDrive",
          "VLC Media Player",
          "Windows Explorer",
        ],
        correctIndex: 1,
      },
      {
        id: "q9",
        topic: "Instalacion",
        prompt: "Al instalar una impresora nueva, el equipo no la reconoce aunque esta conectada. Que debe instalar el tecnico para que funcione correctamente?",
        options: [
          "Una suite ofimatica adicional.",
          "El controlador o driver de la impresora.",
          "Un antivirus actualizado.",
          "Un navegador web nuevo.",
        ],
        correctIndex: 1,
      },
      {
        id: "q10",
        topic: "Buenas practicas",
        prompt: "Despues de instalar el software en los 20 equipos de TechBoyCa, que debe hacer el tecnico antes de entregarlos?",
        options: [
          "Apagar los equipos y guardar los cables.",
          "Verificar que cada programa abre y funciona correctamente y registrarlo en la ficha tecnica.",
          "Instalar juegos para probar el rendimiento.",
          "Cambiar las contrasenas de todos los usuarios sin avisar.",
        ],
        correctIndex: 1,
      },
    ],
    B: [
      {
        id: "q1",
        topic: "Ofimatica",
        prompt: "Un empleado necesita crear una tabla con formulas para calcular el inventario de equipos. Que aplicacion ofimatica es la indicada?",
        options: [
          "LibreOffice Writer o MS Word",
          "LibreOffice Calc o MS Excel",
          "LibreOffice Impress o MS PowerPoint",
          "Bloc de notas",
        ],
        correctIndex: 1,
      },
      {
        id: "q2",
        topic: "Ofimatica",
        prompt: "El tecnico guarda un documento de texto en LibreOffice Writer. Que formato nativo usa ese programa por defecto?",
        options: [
          ".docx",
          ".pdf",
          ".odt",
          ".txt",
        ],
        correctIndex: 2,
      },
      {
        id: "q3",
        topic: "Antivirus",
        prompt: "Un malware que cifra los archivos del usuario y exige un pago para recuperarlos se llama:",
        options: [
          "Spyware",
          "Ransomware",
          "Adware",
          "Keylogger",
        ],
        correctIndex: 1,
      },
      {
        id: "q4",
        topic: "Seguridad",
        prompt: "El tecnico activa Windows Defender en todos los equipos de la empresa. Cual es la funcion principal de ese software?",
        options: [
          "Acelerar la conexion a internet.",
          "Proteger el equipo contra virus, malware y amenazas en tiempo real.",
          "Organizar los archivos automaticamente.",
          "Hacer copias de seguridad en la nube.",
        ],
        correctIndex: 1,
      },
      {
        id: "q5",
        topic: "Diagnostico",
        prompt: "El tecnico quiere saber la temperatura del procesador y la cantidad de RAM instalada sin abrir el equipo. Que tipo de software usa?",
        options: [
          "Un navegador web",
          "Un procesador de texto",
          "Software de diagnostico de hardware como Speccy o CPU-Z",
          "Una hoja de calculo",
        ],
        correctIndex: 2,
      },
      {
        id: "q6",
        topic: "Instalacion",
        prompt: "Al instalar software en una empresa, por que es importante verificar el tipo de licencia?",
        options: [
          "Para cambiar el color del instalador.",
          "Para asegurar el uso legal, evitar multas y contar con soporte tecnico oficial.",
          "Porque las licencias cambian el tamano del programa.",
          "Para poder compartirlo con cualquier persona sin restricciones.",
        ],
        correctIndex: 1,
      },
      {
        id: "q7",
        topic: "Navegadores",
        prompt: "El tecnico activa el modo incognito del navegador en un equipo compartido. Que logra con eso?",
        options: [
          "El equipo se vuelve invisible en la red.",
          "Se borra el historial de navegacion al cerrar la ventana.",
          "El antivirus deja de funcionar.",
          "Se bloquean todas las descargas.",
        ],
        correctIndex: 1,
      },
      {
        id: "q8",
        topic: "Colaboracion",
        prompt: "El gerente de TechBoyCa pide una herramienta para hacer reuniones virtuales con sucursales en otras ciudades. Cual es la mas adecuada?",
        options: [
          "LibreOffice Calc",
          "Zoom, Teams o Google Meet",
          "CrystalDiskInfo",
          "Desfragmentador de disco",
        ],
        correctIndex: 1,
      },
      {
        id: "q9",
        topic: "Instalacion",
        prompt: "Durante una instalacion personalizada, el instalador pregunta que componentes incluir. Que ventaja tiene elegir instalacion personalizada frente a la tipica?",
        options: [
          "Es mas rapida y no necesita reiniciar.",
          "Permite instalar solo los componentes necesarios y evitar bloatware.",
          "Garantiza mayor velocidad del procesador.",
          "No requiere aceptar terminos de licencia.",
        ],
        correctIndex: 1,
      },
      {
        id: "q10",
        topic: "Buenas practicas",
        prompt: "Por que el tecnico debe reiniciar el equipo despues de instalar cierto software?",
        options: [
          "Para que el equipo ahorre bateria.",
          "Para aplicar cambios pendientes del sistema operativo y registrar los nuevos controladores.",
          "Para borrar el historial del navegador.",
          "Para actualizar el antivirus manualmente.",
        ],
        correctIndex: 1,
      },
    ],
    C: [
      {
        id: "q1",
        topic: "Ofimatica",
        prompt: "El tecnico necesita instalar una herramienta para que los empleados hagan presentaciones con diapositivas. Cual de las siguientes es la opcion de codigo abierto?",
        options: [
          "Microsoft PowerPoint",
          "LibreOffice Impress",
          "Adobe Premiere",
          "Google Sheets",
        ],
        correctIndex: 1,
      },
      {
        id: "q2",
        topic: "Ofimatica",
        prompt: "Un empleado guarda un documento en Word (.docx) y lo abre en LibreOffice Writer. Que puede ocurrir con el formato?",
        options: [
          "El archivo se elimina automaticamente.",
          "Puede haber pequenas diferencias en fuentes o tablas por compatibilidad entre formatos.",
          "El documento se convierte en imagen.",
          "El texto desaparece completamente.",
        ],
        correctIndex: 1,
      },
      {
        id: "q3",
        topic: "Antivirus",
        prompt: "Un malware que se camufla dentro de un programa aparentemente legitimo se llama:",
        options: [
          "Gusano",
          "Adware",
          "Troyano",
          "Spyware",
        ],
        correctIndex: 2,
      },
      {
        id: "q4",
        topic: "Seguridad",
        prompt: "El tecnico recomienda no descargar software de paginas no oficiales. Cual es la razon principal?",
        options: [
          "Las paginas no oficiales cobran mas por las descargas.",
          "Los archivos pueden contener malware oculto que infecta el equipo.",
          "El internet es mas lento desde esas paginas.",
          "El software no tendra interfaz grafica.",
        ],
        correctIndex: 1,
      },
      {
        id: "q5",
        topic: "Diagnostico",
        prompt: "El tecnico escribe 'ping 192.168.1.1' en la consola. Para que sirve ese comando?",
        options: [
          "Para formatear el disco duro.",
          "Para verificar si hay conectividad de red con otro equipo o router.",
          "Para instalar controladores de red.",
          "Para abrir el administrador de tareas.",
        ],
        correctIndex: 1,
      },
      {
        id: "q6",
        topic: "Instalacion",
        prompt: "Antes de actualizar el sistema operativo de los equipos de TechBoyCa, que debe hacer el tecnico primero?",
        options: [
          "Desinstalar el antivirus.",
          "Hacer una copia de seguridad de los datos importantes.",
          "Desconectar la impresora.",
          "Borrar los archivos temporales.",
        ],
        correctIndex: 1,
      },
      {
        id: "q7",
        topic: "Navegadores",
        prompt: "El tecnico nota que el navegador carga lento las paginas. Borrar la cache del navegador ayuda porque:",
        options: [
          "Elimina virus del equipo.",
          "Libera espacio de archivos temporales y obliga al navegador a descargar recursos actualizados.",
          "Aumenta la velocidad del procesador.",
          "Actualiza el sistema operativo.",
        ],
        correctIndex: 1,
      },
      {
        id: "q8",
        topic: "Colaboracion",
        prompt: "El tecnico configura una cuenta de correo empresarial en Outlook para cada empleado. Cual es la ventaja del correo electronico frente al mensaje de texto?",
        options: [
          "Es mas rapido que una llamada telefonica.",
          "Permite adjuntar documentos, mantener historial de conversaciones y comunicarse de forma asincrona.",
          "No necesita conexion a internet.",
          "Solo funciona dentro del edificio.",
        ],
        correctIndex: 1,
      },
      {
        id: "q9",
        topic: "Instalacion",
        prompt: "Que informacion debe registrar el tecnico en la ficha tecnica de cada equipo despues de la instalacion?",
        options: [
          "Solo el nombre del empleado que lo usa.",
          "Software instalado, version, tipo de licencia, fecha de instalacion y nombre del tecnico responsable.",
          "Unicamente el numero de serie del equipo.",
          "El color del gabinete y el modelo del monitor.",
        ],
        correctIndex: 1,
      },
      {
        id: "q10",
        topic: "Buenas practicas",
        prompt: "Por que es perjudicial para una empresa no tener documentados los procesos tecnologicos de sus equipos?",
        options: [
          "Porque los equipos consumen mas electricidad.",
          "Porque ante fallas o cambios de tecnico no hay registro de lo instalado, lo que genera retrasos y errores.",
          "Porque el antivirus deja de actualizarse.",
          "Porque los empleados no pueden usar internet.",
        ],
        correctIndex: 1,
      },
    ],
  };
})();
