(function () {
  window.REDES_QUIZ_VARIANTS = {
    A: [
      {
        id: "q1",
        topic: "3.2.1.A",
        prompt: "En la papeleria de la senora Carmen, tres computadores y una impresora comparten recursos dentro del mismo local. Que tipo de red describe mejor ese caso?",
        options: [
          "WAN",
          "MAN",
          "LAN",
          "PAN",
        ],
        correctIndex: 2,
      },
      {
        id: "q2",
        topic: "3.2.1.A",
        prompt: "Que tipo de red se usa normalmente para conectar varias sedes de una misma ciudad?",
        options: [
          "MAN",
          "LAN",
          "PAN",
          "VPN local",
        ],
        correctIndex: 0,
      },
      {
        id: "q3",
        topic: "3.2.1.B",
        prompt: "Cual es la principal ventaja operativa de una topologia en estrella en una oficina pequena?",
        options: [
          "Todos los equipos dependen del mismo cable central sin switch.",
          "Topologia en estrella facilita agregar equipos y aislar fallas por enlace.",
          "Solo funciona con fibra optica.",
          "Obliga a que todos los equipos tengan la misma direccion IP.",
        ],
        correctIndex: 1,
      },
      {
        id: "q4",
        topic: "3.2.1.B",
        prompt: "Si falla el switch central de una red en estrella, que ocurre normalmente?",
        options: [
          "Solo deja de funcionar la impresora.",
          "La red completa queda sin comunicacion interna hasta reemplazarlo.",
          "La red cambia automaticamente a topologia arbol.",
          "Nada, porque el switch no afecta a los equipos finales.",
        ],
        correctIndex: 1,
      },
      {
        id: "q5",
        topic: "3.2.1.C",
        prompt: "Que medio de transmision ofrece mas inmunidad a interferencias electromagneticas?",
        options: [
          "Cable coaxial delgado",
          "Cable UTP Cat5e",
          "Fibra optica",
          "Wi-Fi de 2.4 GHz",
        ],
        correctIndex: 2,
      },
      {
        id: "q6",
        topic: "3.2.1.C",
        prompt: "Para una oficina pequena con bajo presupuesto y distancias cortas, que medio suele ser el mas practico?",
        options: [
          "Cable UTP",
          "Fibra submarina",
          "Enlace satelital",
          "Bluetooth de consumo",
        ],
        correctIndex: 0,
      },
      {
        id: "q7",
        topic: "3.2.1.D",
        prompt: "Que dispositivo toma decisiones de envio entre redes distintas usando direcciones IP?",
        options: [
          "Hub",
          "Router",
          "Patch panel",
          "Tarjeta de sonido",
        ],
        correctIndex: 1,
      },
      {
        id: "q8",
        topic: "3.2.1.D",
        prompt: "Por que el hub casi no se usa en redes modernas?",
        options: [
          "Porque distribuye el trafico a todos los puertos y genera mas colisiones.",
          "Porque solo funciona con direcciones IPv6.",
          "Porque reemplaza al router en internet.",
          "Porque no puede conectarse a un switch.",
        ],
        correctIndex: 0,
      },
      {
        id: "q9",
        topic: "3.2.1.E",
        prompt: "En que capa del modelo OSI trabaja principalmente el router tradicional?",
        options: [
          "Capa 1 Fisica",
          "Capa 2 Enlace",
          "Capa 3 Red",
          "Capa 7 Aplicacion",
        ],
        correctIndex: 2,
      },
      {
        id: "q10",
        topic: "3.2.1.E",
        prompt: "Que protocolo del conjunto TCP/IP se asocia directamente con el direccionamiento logico y el encaminamiento?",
        options: [
          "IP",
          "HTTP",
          "FTP",
          "HTML",
        ],
        correctIndex: 0,
      },
    ],
    B: [
      {
        id: "q1",
        topic: "3.2.1.A",
        prompt: "Que red cubre una extension geografica mayor, como paises o continentes?",
        options: [
          "LAN",
          "WAN",
          "PAN",
          "Bus",
        ],
        correctIndex: 1,
      },
      {
        id: "q2",
        topic: "3.2.1.A",
        prompt: "Una red dentro de un edificio, con alcance limitado y alta velocidad local, se clasifica como:",
        options: [
          "MAN",
          "WAN",
          "LAN",
          "SAN publica",
        ],
        correctIndex: 2,
      },
      {
        id: "q3",
        topic: "3.2.1.B",
        prompt: "En que situacion tendria sentido considerar una topologia en arbol?",
        options: [
          "Cuando se necesita organizar segmentos jerarquicos por areas o pisos.",
          "Cuando no existe ningun dispositivo central.",
          "Cuando todos los computadores comparten un unico cable lineal.",
          "Cuando la red solo conecta dos telefonos.",
        ],
        correctIndex: 0,
      },
      {
        id: "q4",
        topic: "3.2.1.B",
        prompt: "Que caracteriza a una topologia en bus frente a la estrella?",
        options: [
          "Cada equipo tiene su enlace dedicado al switch.",
          "Los equipos comparten un medio principal comun.",
          "Siempre necesita un router por puesto.",
          "No puede transportar datos digitales.",
        ],
        correctIndex: 1,
      },
      {
        id: "q5",
        topic: "3.2.1.C",
        prompt: "Cual es una razon tecnica para preferir Cat6 sobre Cat5e en una nueva instalacion?",
        options: [
          "Opera sin conectores RJ45.",
          "Ofrece mejor desempeno para mayores velocidades y menor ruido.",
          "No requiere normas de cableado.",
          "Se usa solo en enlaces satelitales.",
        ],
        correctIndex: 1,
      },
      {
        id: "q6",
        topic: "3.2.1.C",
        prompt: "Que medio resulta mas vulnerable a interferencias y obstaculos del entorno?",
        options: [
          "Fibra optica monomodo",
          "Cableado estructurado blindado",
          "Wi-Fi",
          "Latiguillo de fibra",
        ],
        correctIndex: 2,
      },
      {
        id: "q7",
        topic: "3.2.1.D",
        prompt: "Que dispositivo aprende direcciones MAC y reenvia tramas dentro de la misma LAN de forma mas eficiente?",
        options: [
          "Hub",
          "Switch",
          "Router",
          "UPS",
        ],
        correctIndex: 1,
      },
      {
        id: "q8",
        topic: "3.2.1.D",
        prompt: "Que funcion cumple un access point en una red local?",
        options: [
          "Convierte automaticamente una WAN en MAN.",
          "Proporciona acceso inalambrico a la red.",
          "Asigna mascaras por defecto a todos los hosts.",
          "Reemplaza el cableado estructurado completo.",
        ],
        correctIndex: 1,
      },
      {
        id: "q9",
        topic: "3.2.1.E",
        prompt: "En que capa del modelo OSI trabaja principalmente un switch tradicional?",
        options: [
          "Capa 2 Enlace de datos",
          "Capa 4 Transporte",
          "Capa 6 Presentacion",
          "Capa 7 Aplicacion",
        ],
        correctIndex: 0,
      },
      {
        id: "q10",
        topic: "3.2.1.E",
        prompt: "Que relacion general existe entre OSI y TCP/IP?",
        options: [
          "OSI describe un modelo de referencia y TCP/IP agrupa funciones en menos capas operativas.",
          "Son el mismo modelo con nombres distintos y siete capas exactas.",
          "TCP/IP no usa protocolos reales.",
          "OSI solo sirve para topologias fisicas.",
        ],
        correctIndex: 0,
      },
    ],
    C: [
      {
        id: "q1",
        topic: "3.2.1.A",
        prompt: "Que opcion describe mejor una red MAN?",
        options: [
          "Red personal entre audifonos y celular",
          "Red local de una sola oficina",
          "Red que interconecta varios puntos dentro de una misma ciudad",
          "Red exclusiva de routers domesticos",
        ],
        correctIndex: 2,
      },
      {
        id: "q2",
        topic: "3.2.1.A",
        prompt: "Internet es un ejemplo tipico de:",
        options: [
          "LAN",
          "WAN",
          "PAN",
          "Bus local",
        ],
        correctIndex: 1,
      },
      {
        id: "q3",
        topic: "3.2.1.B",
        prompt: "Que ventaja ofrece la estrella frente al bus para mantenimiento?",
        options: [
          "Permite detectar mejor que enlace presenta una falla.",
          "Elimina la necesidad de switch.",
          "Impide completamente las caidas de red.",
          "Hace innecesario el direccionamiento IP.",
        ],
        correctIndex: 0,
      },
      {
        id: "q4",
        topic: "3.2.1.B",
        prompt: "Que afirmacion representa mejor la topologia en anillo?",
        options: [
          "Cada host depende de una unica nube publica.",
          "Los equipos se enlazan formando un circuito cerrado.",
          "Siempre usa direccionamiento clase C.",
          "Solo existe en redes Wi-Fi domesticas.",
        ],
        correctIndex: 1,
      },
      {
        id: "q5",
        topic: "3.2.1.C",
        prompt: "Cuando es mas razonable elegir fibra optica en vez de UTP?",
        options: [
          "Cuando se requiere mayor distancia y alto ancho de banda.",
          "Cuando se necesita la opcion mas economica para tramos muy cortos.",
          "Cuando no habra ningun equipo de red.",
          "Cuando el enlace es solo por Bluetooth.",
        ],
        correctIndex: 0,
      },
      {
        id: "q6",
        topic: "3.2.1.C",
        prompt: "Cual es una limitacion tipica del cable UTP en ethernet cobre?",
        options: [
          "Solo transmite audio analogico.",
          "Su longitud recomendada por tramo es limitada frente a fibra.",
          "No puede usar conectores.",
          "No funciona en redes LAN.",
        ],
        correctIndex: 1,
      },
      {
        id: "q7",
        topic: "3.2.1.D",
        prompt: "Que dispositivo conecta una LAN cableada con clientes inalambricos dentro del mismo entorno local?",
        options: [
          "Access point",
          "Hub pasivo",
          "Repetidor telefonico analogico",
          "Monitor",
        ],
        correctIndex: 0,
      },
      {
        id: "q8",
        topic: "3.2.1.D",
        prompt: "Cuando basta con usar un switch y no necesariamente un router?",
        options: [
          "Cuando todos los equipos se comunican dentro de la misma red local.",
          "Cuando se debe salir a internet por varias subredes remotas.",
          "Cuando se necesita traducir nombres DNS publicos.",
          "Cuando se requiere interconectar ciudades distintas.",
        ],
        correctIndex: 0,
      },
      {
        id: "q9",
        topic: "3.2.1.E",
        prompt: "Que capa OSI se asocia con el envio de bits por el medio fisico?",
        options: [
          "Capa 1 Fisica",
          "Capa 3 Red",
          "Capa 5 Sesion",
          "Capa 7 Aplicacion",
        ],
        correctIndex: 0,
      },
      {
        id: "q10",
        topic: "3.2.1.E",
        prompt: "Cual protocolo pertenece claramente a la capa de aplicacion del conjunto TCP/IP?",
        options: [
          "HTTP",
          "IP",
          "ARP",
          "Ethernet",
        ],
        correctIndex: 0,
      },
    ],
  };
})();
