(function () {
  window.REDES_QUIZ_VARIANTS = {
    A: [
      {
        id: "q1",
        topic: "3.2.1.A",
        prompt: "En la papeleria de la senora Carmen, tres computadores y una impresora comparten recursos dentro del mismo local. Que tipo de red describe mejor ese caso?",
        options: [
          "WAN",
          "MAN",
          "LAN",
          "PAN",
        ],
        correctIndex: 2,
      },
      {
        id: "q2",
        topic: "3.2.1.A",
        prompt: "Que tipo de red se usa normalmente para conectar varias sedes de una misma ciudad?",
        options: [
          "MAN",
          "LAN",
          "PAN",
          "VPN local",
        ],
        correctIndex: 0,
      },
      {
        id: "q3",
        topic: "3.2.1.B",
        prompt: "Cual es la principal ventaja operativa de una topologia en estrella en una oficina pequena?",
        options: [
          "Todos los equipos dependen del mismo cable central sin switch.",
          "Topologia en estrella facilita agregar equipos y aislar fallas por enlace.",
          "Solo funciona con fibra optica.",
          "Obliga a que todos los equipos tengan la misma direccion IP.",
        ],
        correctIndex: 1,
      },
      {
        id: "q4",
        topic: "3.2.1.B",
        prompt: "Si falla el switch central de una red en estrella, que ocurre normalmente?",
        options: [
          "Solo deja de funcionar la impresora.",
          "La red completa queda sin comunicacion interna hasta reemplazarlo.",
          "La red cambia automaticamente a topologia arbol.",
          "Nada, porque el switch no afecta a los equipos finales.",
        ],
        correctIndex: 1,
      },
      {
        id: "q5",
        topic: "3.2.1.C",
        prompt: "Que medio de transmision ofrece mas inmunidad a interferencias electromagneticas?",
        options: [
          "Cable coaxial delgado",
          "Cable UTP Cat5e",
          "Fibra optica",
          "Wi-Fi de 2.4 GHz",
        ],
        correctIndex: 2,
      },
      {
        id: "q6",
        topic: "3.2.1.C",
        prompt: "Para una oficina pequena con bajo presupuesto y distancias cortas, que medio suele ser el mas practico?",
        options: [
          "Cable UTP",
          "Fibra submarina",
          "Enlace satelital",
          "Bluetooth de consumo",
        ],
        correctIndex: 0,
      },
      {
        id: "q7",
        topic: "3.2.1.D",
        prompt: "Que dispositivo toma decisiones de envio entre redes distintas usando direcciones IP?",
        options: [
          "Hub",
          "Router",
          "Patch panel",
          "Tarjeta de sonido",
        ],
        correctIndex: 1,
      },
      {
        id: "q8",
        topic: "3.2.1.D",
        prompt: "Por que el hub casi no se usa en redes modernas?",
        options: [
          "Porque distribuye el trafico a todos los puertos y genera mas colisiones.",
          "Porque solo funciona con direcciones IPv6.",
          "Porque reemplaza al router en internet.",
          "Porque no puede conectarse a un switch.",
        ],
        correctIndex: 0,
      },
      {
        id: "q9",
        topic: "3.2.1.E",
        prompt: "En que capa del modelo OSI trabaja principalmente el router tradicional?",
        options: [
          "Capa 1 Fisica",
          "Capa 2 Enlace",
          "Capa 3 Red",
          "Capa 7 Aplicacion",
        ],
        correctIndex: 2,
      },
      {
        id: "q10",
        topic: "3.2.1.E",
        prompt: "Que protocolo del conjunto TCP/IP se asocia directamente con el direccionamiento logico y el encaminamiento?",
        options: [
          "IP",
          "HTTP",
          "FTP",
          "HTML",
        ],
        correctIndex: 0,
      },
    ],
    B: [
      {
        id: "q1",
        topic: "3.2.1.A",
        prompt: "Que red cubre una extension geografica mayor, como paises o continentes?",
        options: [
          "LAN",
          "WAN",
          "PAN",
          "Bus",
        ],
        correctIndex: 1,
      },
      {
        id: "q2",
        topic: "3.2.1.A",
        prompt: "Una red dentro de un edificio, con alcance limitado y alta velocidad local, se clasifica como:",
        options: [
          "MAN",
          "WAN",
          "LAN",
          "SAN publica",
        ],
        correctIndex: 2,
      },
      {
        id: "q3",
        topic: "3.2.1.B",
        prompt: "En que situacion tendria sentido considerar una topologia en arbol?",
        options: [
          "Cuando se necesita organizar segmentos jerarquicos por areas o pisos.",
          "Cuando no existe ningun dispositivo central.",
          "Cuando todos los computadores comparten un unico cable lineal.",
          "Cuando la red solo conecta dos telefonos.",
        ],
        correctIndex: 0,
      },
      {
        id: "q4",
        topic: "3.2.1.B",
        prompt: "Que caracteriza a una topologia en bus frente a la estrella?",
        options: [
          "Cada equipo tiene su enlace dedicado al switch.",
          "Los equipos comparten un medio principal comun.",
          "Siempre necesita un router por puesto.",
          "No puede transportar datos digitales.",
        ],
        correctIndex: 1,
      },
      {
        id: "q5",
        topic: "3.2.1.C",
        prompt: "Cual es una razon tecnica para preferir Cat6 sobre Cat5e en una nueva instalacion?",
        options: [
          "Opera sin conectores RJ45.",
          "Ofrece mejor desempeno para mayores velocidades y menor ruido.",
          "No requiere normas de cableado.",
          "Se usa solo en enlaces satelitales.",
        ],
        correctIndex: 1,
      },
      {
        id: "q6",
        topic: "3.2.1.C",
        prompt: "Que medio resulta mas vulnerable a interferencias y obstaculos del entorno?",
        options: [
          "Fibra optica monomodo",
          "Cableado estructurado blindado",
          "Wi-Fi",
          "Latiguillo de fibra",
        ],
        correctIndex: 2,
      },
      {
        id: "q7",
        topic: "3.2.1.D",
        prompt: "Que dispositivo aprende direcciones MAC y reenvia tramas dentro de la misma LAN de forma mas eficiente?",
        options: [
          "Hub",
          "Switch",
          "Router",
          "UPS",
        ],
        correctIndex: 1,
      },
      {
        id: "q8",
        topic: "3.2.1.D",
        prompt: "Que funcion cumple un access point en una red local?",
        options: [
          "Convierte automaticamente una WAN en MAN.",
          "Proporciona acceso inalambrico a la red.",
          "Asigna mascaras por defecto a todos los hosts.",
          "Reemplaza el cableado estructurado completo.",
        ],
        correctIndex: 1,
      },
      {
        id: "q9",
        topic: "3.2.1.E",
        prompt: "En que capa del modelo OSI trabaja principalmente un switch tradicional?",
        options: [
          "Capa 2 Enlace de datos",
          "Capa 4 Transporte",
          "Capa 6 Presentacion",
          "Capa 7 Aplicacion",
        ],
        correctIndex: 0,
      },
      {
        id: "q10",
        topic: "3.2.1.E",
        prompt: "Que relacion general existe entre OSI y TCP/IP?",
        options: [
          "OSI describe un modelo de referencia y TCP/IP agrupa funciones en menos capas operativas.",
          "Son el mismo modelo con nombres distintos y siete capas exactas.",
          "TCP/IP no usa protocolos reales.",
          "OSI solo sirve para topologias fisicas.",
        ],
        correctIndex: 0,
      },
    ],
    C: [
      {
        id: "q1",
        topic: "3.2.1.A",
        prompt: "Que opcion describe mejor una red MAN?",
        options: [
          "Red personal entre audifonos y celular",
          "Red local de una sola oficina",
          "Red que interconecta varios puntos dentro de una misma ciudad",
          "Red exclusiva de routers domesticos",
        ],
        correctIndex: 2,
      },
      {
        id: "q2",
        topic: "3.2.1.A",
        prompt: "Internet es un ejemplo tipico de:",
        options: [
          "LAN",
          "WAN",
          "PAN",
          "Bus local",
        ],
        correctIndex: 1,
      },
      {
        id: "q3",
        topic: "3.2.1.B",
        prompt: "Que ventaja ofrece la estrella frente al bus para mantenimiento?",
        options: [
          "Permite detectar mejor que enlace presenta una falla.",
          "Elimina la necesidad de switch.",
          "Impide completamente las caidas de red.",
          "Hace innecesario el direccionamiento IP.",
        ],
        correctIndex: 0,
      },
      {
        id: "q4",
        topic: "3.2.1.B",
        prompt: "Que afirmacion representa mejor la topologia en anillo?",
        options: [
          "Cada host depende de una unica nube publica.",
          "Los equipos se enlazan formando un circuito cerrado.",
          "Siempre usa direccionamiento clase C.",
          "Solo existe en redes Wi-Fi domesticas.",
        ],
        correctIndex: 1,
      },
      {
        id: "q5",
        topic: "3.2.1.C",
        prompt: "Cuando es mas razonable elegir fibra optica en vez de UTP?",
        options: [
          "Cuando se requiere mayor distancia y alto ancho de banda.",
          "Cuando se necesita la opcion mas economica para tramos muy cortos.",
          "Cuando no habra ningun equipo de red.",
          "Cuando el enlace es solo por Bluetooth.",
        ],
        correctIndex: 0,
      },
      {
        id: "q6",
        topic: "3.2.1.C",
        prompt: "Cual es una limitacion tipica del cable UTP en ethernet cobre?",
        options: [
          "Solo transmite audio analogico.",
          "Su longitud recomendada por tramo es limitada frente a fibra.",
          "No puede usar conectores.",
          "No funciona en redes LAN.",
        ],
        correctIndex: 1,
      },
      {
        id: "q7",
        topic: "3.2.1.D",
        prompt: "Que dispositivo conecta una LAN cableada con clientes inalambricos dentro del mismo entorno local?",
        options: [
          "Access point",
          "Hub pasivo",
          "Repetidor telefonico analogico",
          "Monitor",
        ],
        correctIndex: 0,
      },
      {
        id: "q8",
        topic: "3.2.1.D",
        prompt: "Cuando basta con usar un switch y no necesariamente un router?",
        options: [
          "Cuando todos los equipos se comunican dentro de la misma red local.",
          "Cuando se debe salir a internet por varias subredes remotas.",
          "Cuando se necesita traducir nombres DNS publicos.",
          "Cuando se requiere interconectar ciudades distintas.",
        ],
        correctIndex: 0,
      },
      {
        id: "q9",
        topic: "3.2.1.E",
        prompt: "Que capa OSI se asocia con el envio de bits por el medio fisico?",
        options: [
          "Capa 1 Fisica",
          "Capa 3 Red",
          "Capa 5 Sesion",
          "Capa 7 Aplicacion",
        ],
        correctIndex: 0,
      },
      {
        id: "q10",
        topic: "3.2.1.E",
        prompt: "Cual protocolo pertenece claramente a la capa de aplicacion del conjunto TCP/IP?",
        options: [
          "HTTP",
          "IP",
          "ARP",
          "Ethernet",
        ],
        correctIndex: 0,
      },
    ],
  };
})();

(function () {
  window.REDES_IP_QUIZ_VARIANTS = {
    A: [
      {
        id: "q1",
        topic: "3.3.1",
        prompt: "¿Cuántos octetos tiene una dirección IPv4?",
        options: ["3", "4", "6", "8"],
        correctIndex: 1,
      },
      {
        id: "q2",
        topic: "3.3.1",
        prompt: "¿Qué rango válido puede tener cada octeto de una dirección IPv4?",
        options: ["0 a 128", "1 a 254", "0 a 255", "0 a 512"],
        correctIndex: 2,
      },
      {
        id: "q3",
        topic: "3.3.1",
        prompt: "¿Por qué no pueden existir dos dispositivos con la misma IP en la misma red?",
        options: [
          "Porque el router no tiene cable suficiente para los dos.",
          "Porque habría un conflicto que impediría la comunicación de uno o ambos equipos.",
          "Porque el switch apaga automáticamente el equipo duplicado.",
          "Porque el DNS no puede resolver dos nombres iguales.",
        ],
        correctIndex: 1,
      },
      {
        id: "q4",
        topic: "3.3.2",
        prompt: "¿Cuál es la máscara de subred por defecto de una dirección Clase C?",
        options: ["255.0.0.0", "255.255.0.0", "255.255.255.0", "255.255.255.255"],
        correctIndex: 2,
      },
      {
        id: "q5",
        topic: "3.3.2",
        prompt: "¿Cuál de las siguientes es una dirección IP privada de Clase A?",
        options: ["10.0.0.1", "172.32.0.1", "192.168.0.1", "200.0.0.1"],
        correctIndex: 0,
      },
      {
        id: "q6",
        topic: "3.3.2",
        prompt: "¿Por qué las IPs privadas no pueden usarse directamente en Internet?",
        options: [
          "Porque son demasiado lentas para transmitir datos.",
          "Porque no son únicas globalmente y están reservadas para redes internas.",
          "Porque el DNS público las rechaza.",
          "Porque solo funcionan con fibra óptica.",
        ],
        correctIndex: 1,
      },
      {
        id: "q7",
        topic: "3.3.3",
        prompt: "¿Para qué sirve el gateway predeterminado?",
        options: [
          "Traduce nombres de dominio a direcciones IP.",
          "Es la dirección del router que permite al equipo salir hacia otras redes e Internet.",
          "Asigna automáticamente la IP al dispositivo.",
          "Indica cuántos hosts puede tener la red.",
        ],
        correctIndex: 1,
      },
      {
        id: "q8",
        topic: "3.3.3",
        prompt: "¿Qué pasaría si el gateway está mal configurado en un equipo?",
        options: [
          "La red local dejaría de funcionar completamente.",
          "No se podría acceder a Internet aunque la red local funcione bien.",
          "El switch dejaría de aprender direcciones MAC.",
          "La dirección IP del equipo cambiaría automáticamente.",
        ],
        correctIndex: 1,
      },
      {
        id: "q9",
        topic: "3.3.3",
        prompt: "¿Cuál es la función del servidor DNS?",
        options: [
          "Asignar direcciones IP automáticamente a los dispositivos.",
          "Traducir nombres de dominio como 'www.sena.edu.co' a direcciones IP.",
          "Cifrar el tráfico entre el equipo y el router.",
          "Conectar dos redes físicas diferentes.",
        ],
        correctIndex: 1,
      },
      {
        id: "q10",
        topic: "3.3.3",
        prompt: "¿Cuál parámetro de red le indica al equipo cuántos bits pertenecen a la red y cuántos al host?",
        options: ["Gateway", "DNS", "Dirección IP", "Máscara de subred"],
        correctIndex: 3,
      },
    ],
    B: [
      {
        id: "q1",
        topic: "3.3.1",
        prompt: "¿Cuántos bits tiene una dirección IPv4?",
        options: ["16", "32", "64", "128"],
        correctIndex: 1,
      },
      {
        id: "q2",
        topic: "3.3.1",
        prompt: "La dirección 192.168.1.300 es inválida porque:",
        options: [
          "Tiene muy pocos octetos.",
          "Un octeto no puede superar el valor 255.",
          "Las IPs privadas no pueden usar el número 300.",
          "El tercer octeto no puede ser 1.",
        ],
        correctIndex: 1,
      },
      {
        id: "q3",
        topic: "3.3.1",
        prompt: "En la dirección 192.168.1.45 con máscara 255.255.255.0, ¿cuál es la parte de red?",
        options: ["45", "192.168.1", "192", "1.45"],
        correctIndex: 1,
      },
      {
        id: "q4",
        topic: "3.3.2",
        prompt: "¿Cuál es el rango del primer octeto para IPs de Clase B?",
        options: ["1 a 126", "128 a 191", "192 a 223", "224 a 239"],
        correctIndex: 1,
      },
      {
        id: "q5",
        topic: "3.3.2",
        prompt: "¿Cuál rango de IP privada corresponde a la Clase B?",
        options: [
          "10.0.0.0 – 10.255.255.255",
          "172.16.0.0 – 172.31.255.255",
          "192.168.0.0 – 192.168.255.255",
          "169.254.0.0 – 169.254.255.255",
        ],
        correctIndex: 1,
      },
      {
        id: "q6",
        topic: "3.3.2",
        prompt: "¿Cuántos hosts puede manejar una red Clase C con máscara 255.255.255.0?",
        options: ["254", "65 534", "16 millones", "2"],
        correctIndex: 0,
      },
      {
        id: "q7",
        topic: "3.3.3",
        prompt: "La máscara de subred 255.255.255.0 indica que:",
        options: [
          "Los primeros 3 octetos identifican la red y el último identifica el host.",
          "Solo hay un host posible en la red.",
          "Los primeros 8 bits son para el host.",
          "La red es de tipo WAN.",
        ],
        correctIndex: 0,
      },
      {
        id: "q8",
        topic: "3.3.3",
        prompt: "¿Cuál parámetro de red es la 'puerta de salida' del computador hacia Internet?",
        options: ["Dirección IP", "Máscara de subred", "Gateway predeterminado", "Dirección MAC"],
        correctIndex: 2,
      },
      {
        id: "q9",
        topic: "3.3.3",
        prompt: "El servidor DNS 8.8.8.8 es reconocido porque es:",
        options: [
          "La IP del servidor del SENA.",
          "El servidor DNS público de Google.",
          "El gateway predeterminado universal.",
          "La IP de loopback del router.",
        ],
        correctIndex: 1,
      },
      {
        id: "q10",
        topic: "3.3.3",
        prompt: "Un equipo tiene IP 192.168.1.50, máscara 255.255.255.0 y gateway 192.168.1.1. ¿Cuál es la función del valor 192.168.1.1?",
        options: [
          "Es la dirección del propio equipo.",
          "Es la dirección del router por donde el equipo sale a Internet.",
          "Es la dirección del servidor DNS.",
          "Indica el número de hosts disponibles.",
        ],
        correctIndex: 1,
      },
    ],
    C: [
      {
        id: "q1",
        topic: "3.3.1",
        prompt: "¿Cuál afirmación sobre los octetos de una IPv4 es correcta?",
        options: [
          "Cada octeto puede tener cualquier valor entre 0 y 512.",
          "Una IPv4 tiene exactamente 4 octetos, cada uno entre 0 y 255.",
          "Una IPv4 tiene 6 octetos separados por dos puntos.",
          "Los octetos de la IPv4 solo pueden ser números pares.",
        ],
        correctIndex: 1,
      },
      {
        id: "q2",
        topic: "3.3.1",
        prompt: "¿Qué ocurre cuando dos dispositivos en la misma red tienen la misma dirección IP?",
        options: [
          "Ambos funcionan a la mitad de velocidad.",
          "Se produce un conflicto que interrumpe la comunicación de uno o ambos equipos.",
          "El switch asigna automáticamente una IP nueva al segundo equipo.",
          "El gateway los desconecta de Internet.",
        ],
        correctIndex: 1,
      },
      {
        id: "q3",
        topic: "3.3.1",
        prompt: "¿Qué representa la parte de 'host' en una dirección IPv4?",
        options: [
          "El país donde se encuentra el equipo.",
          "El número específico que identifica al dispositivo dentro de su red.",
          "La velocidad de conexión del equipo en Mbps.",
          "El tipo de cable que usa el equipo.",
        ],
        correctIndex: 1,
      },
      {
        id: "q4",
        topic: "3.3.2",
        prompt: "Un técnico ve la IP 172.20.5.3 en un equipo. ¿A qué clase de IP privada pertenece?",
        options: [
          "Clase A privada (10.x.x.x)",
          "Clase B privada (172.16–31.x.x)",
          "Clase C privada (192.168.x.x)",
          "IP pública",
        ],
        correctIndex: 1,
      },
      {
        id: "q5",
        topic: "3.3.2",
        prompt: "¿Cuál afirmación sobre la Clase C de IP es correcta?",
        options: [
          "Soporta millones de hosts por red.",
          "Su máscara por defecto es 255.255.255.0 y permite hasta 254 hosts.",
          "Su primer octeto va de 128 a 191.",
          "No tiene rango de IPs privadas.",
        ],
        correctIndex: 1,
      },
      {
        id: "q6",
        topic: "3.3.2",
        prompt: "¿Cuál es el rango del primer octeto para las IPs de Clase A?",
        options: ["1 a 126", "128 a 191", "192 a 223", "0 a 255"],
        correctIndex: 0,
      },
      {
        id: "q7",
        topic: "3.3.3",
        prompt: "¿Cuál parámetro de red le dice al equipo qué bits corresponden a la red y cuáles al host?",
        options: ["Gateway", "DNS", "Máscara de subred", "Dirección MAC"],
        correctIndex: 2,
      },
      {
        id: "q8",
        topic: "3.3.3",
        prompt: "Un estudiante puede acceder a otros equipos en su salón pero no puede abrir páginas web. ¿Cuál parámetro es más probable que esté mal configurado?",
        options: [
          "Dirección IP local.",
          "Máscara de subred.",
          "Gateway predeterminado.",
          "Dirección MAC.",
        ],
        correctIndex: 2,
      },
      {
        id: "q9",
        topic: "3.3.3",
        prompt: "¿Qué diferencia al DNS del gateway?",
        options: [
          "El DNS traduce nombres de dominio a IPs; el gateway es la salida de la red hacia otras redes.",
          "Son lo mismo con distinto nombre.",
          "El gateway traduce nombres y el DNS enruta los paquetes.",
          "El DNS asigna IPs y el gateway asigna MACs.",
        ],
        correctIndex: 0,
      },
      {
        id: "q10",
        topic: "3.3.3",
        prompt: "¿Es posible que la red local funcione sin servidor DNS configurado?",
        options: [
          "No, el DNS es obligatorio para cualquier comunicación en red.",
          "Sí, porque la red local usa IPs directamente y no necesita resolver nombres para comunicarse internamente.",
          "No, porque el gateway requiere DNS para enrutar paquetes.",
          "Sí, pero solo si hay más de un router.",
        ],
        correctIndex: 1,
      },
    ],
  };
})();
